name: Build and deploy Simply-links

on:
  push:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Grant permission to execute file
        run: chmod +x ./mvnw

      - name: Run Tests
        run: ./mvnw test

      - name: Acknowledgement
        run: echo "All test successfully completed."

  # second job
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Set up Docker
       uses: docker/setup-buildx-action@v3

     - name: Setup Java 17
       uses: actions/setup-java@v4
       with:
         distribution: 'zulu'
         java-version: '17'

     - name: Build Jar file
       run: ./mvnw clean package -DskipTests

     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_PASS }}

     - name: Build Docker Image
       run: docker build -t your-dockerhub-username/simply-links:latest .

     - name: Push Docker Image
       run: docker push your-dockerhub-username/simply-links:latest

     - name: Acknowledgement
       run: echo "Image is pushed to dockerhub."



